version: '3.1'

services:
  node:
    build: ./node
    ports: 
      - "80:80"
    depends_on:
      - mysql   
    entrypoint: node app3.js
    volumes:
      - /home/ec2-user/crypto/node:/hasapian
    container_name: node 
  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_DATABASE: cryptoDB
    expose:
      - "3306"
    volumes:
      - /home/ec2-user/crypto/data:/var/lib/mysql 
    container_name: mysql
